import { describe, it, expect } from 'vitest'
import { mount, config } from '@vue/test-utils'
import Table from './Table.vue'
import styles from '#dd/styles/Table.module.css'

config.global.components = {
  DdLoading: { template: '<div class="dd-loading-stub">Loading...</div>' }
}

describe('Table primitive', () => {
  const sampleColumns = [
    { key: 'id', title: 'ID' },
    { key: 'name', title: 'Name' },
    { key: 'status', title: 'Status' }
  ]

  const sampleData = [
    { id: 1, name: 'Alice', status: 'Active' },
    { id: 2, name: 'Bob', status: 'Inactive' }
  ]

  it('renders standard table columns and data rows', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: sampleData
      }
    })

    // Wrapper generated by useBaseComponent
    expect(wrapper.classes()).toContain(styles.wrapper)

    // Check structure
    const thaElements = wrapper.findAll(`th.${styles.th}`)
    expect(thaElements.length).toBe(3)
    expect(thaElements[0]!.text()).toContain('ID')

    // 2 actual data rows (empty states should not exist)
    const tbodies = wrapper.findAll('tbody > tr')
    expect(tbodies.length).toBe(2)

    // First row test
    const firstRowTds = tbodies[0]!.findAll('td')
    expect(firstRowTds.length).toBe(3)
    expect(firstRowTds[1]!.text()).toContain('Alice')
  })

  it('renders dynamic scoped slots dynamically based on column key', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: sampleData
      },
      slots: {
        'cell-status': `<template #cell-status="{ value }">
            <span class="custom-badge">{{ value }}!</span>
          </template>`
      }
    })

    const customBadges = wrapper.findAll('.custom-badge')
    expect(customBadges.length).toBe(2)
    expect(customBadges[0]!.text()).toBe('Active!')
    expect(customBadges[1]!.text()).toBe('Inactive!')
  })

  it('renders an empty state row when data is empty', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: []
      }
    })

    const rows = wrapper.findAll('tbody > tr')
    expect(rows.length).toBe(1)
    expect(rows[0]!.classes()).toContain(styles['empty-row'])
    expect(rows[0]!.text()).toContain('No data available')
  })

  it('allows overriding empty state slot', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: []
      },
      slots: {
        empty: '<div class="custom-empty">Custom empty message</div>'
      }
    })

    expect(wrapper.find('.custom-empty').exists()).toBe(true)
    expect(wrapper.text()).toContain('Custom empty message')
  })

  it('renders loading indicator alone when no data and loading is true', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: [],
        loading: true
      }
    })

    const rows = wrapper.findAll('tbody > tr')
    expect(rows.length).toBe(1)
    expect(rows[0]!.classes()).toContain(styles['loading-row']) // Exclusively loading row
    expect(rows[0]!.classes()).not.toContain(styles['empty-row'])
  })

  it('renders data and loading indicator overlapping row when data exists and loading is true', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: sampleData,
        loading: true
      }
    })

    const rows = wrapper.findAll('tbody > tr')
    // 2 data rows + 1 overlay loading row at the bottom
    expect(rows.length).toBe(3)
    expect(rows[2]!.classes()).toContain(styles['loading-row'])
    expect(rows[2]!.text()).toContain('Updating table...') // sr-only text
  })

  it('renders error row priority when isInvalid', () => {
    const wrapper = mount(Table, {
      props: {
        columns: sampleColumns,
        data: sampleData,
        isInvalid: true,
        errorMessage: 'Connection failed API'
      }
    })

    const rows = wrapper.findAll('tbody > tr')
    expect(rows.length).toBe(1) // Assuming it replaces entire table display body if error
    expect(rows[0]!.classes()).toContain(styles['error-row'])
    expect(rows[0]!.text()).toContain('Connection failed API')
  })
})
